### ISSUE TITLE
INVALID_PROTOBUF Protobuf parsing failed

### ISSUE THREAD

**Issue by treitmaier** [unmute-tech/voice-search-server#1]
Any idea why I'm running into this error: `a onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.`

The full trace is here, in case it helps: 
```
voice-search-server ❯ api_port=8080        
num_workers=10
model_dir=model
data_dir=data
python3 server.py $api_port $num_workers $model_dir $data_dir
Process Process-1:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-2:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-3:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-4:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-5:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-6:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-7:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-8:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-9:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_mode
l)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
Process Process-10:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 90, in _run_server
    asr = create_asr(model_dir)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 12, in create_asr
    xlsr_model = load_xlsr_model(model_path)
  File "/home/thomas/tmp/voice-search-server/lib/asr.py", line 20, in load_xlsr_model
    xlsr_model = rt.InferenceSession(f'{path}/xls_r_300m_18.onnx', sess_opt)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/thomas/.conda/envs/voice-search-server/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model/xls_r_300m_18.onnx failed:Protobuf parsing failed.
```

**Comment by ondrejklejch** [comment]
What is the md5sum of your `model/xls_r_300m_18.onnx`? And how much memory do you have?

**Comment by treitmaier** [comment]
I'm running it on a linux server with 32GB of memory.

md5sum model/xls_r_300m_18.onnx:
`87e2c519beb8899e7fb67f215537ef98  model/xls_r_300m_18.onnx`

**Comment by ondrejklejch** [comment]
The md5sum should be:
```e0d1ab8a5555fc72554f2b733a5dcdc4  model/xls_r_300m_18.onnx```

The model files are stored with [git-lfs](https://git-lfs.com/), do you have it on your system?
